spring :
  application:
    name: integration-grafana

server:
  port: 8081

management:
  endpoints:
    enablad-by-default: false #Desativa todos os outros endpoints que não estãos sendo usados;
    web:
      exposure:
        include: 'health, prometheus' #Para exibir todos enpoints, deve passar o *;
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true